[package]
edition = "2021"
name = "led_game"
version = "0.1.0"
authors = ["Brad Gibson <u007d@humanenginuity.com>"]
resolver = "2"

[dependencies]
defmt = "0.3.8"
defmt-rtt = "0.4.1"
panic-probe = { version = "0.3", features = ["print-defmt"] }

embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embedded-io = "0.6.1"
embedded-io-async = "0.6.1"
embedded-storage = "0.3.1"

cortex-m-rt = "0.7.3"
cortex-m = { version = "0.7.7" }


embassy-executor = { git = "https://github.com/embassy-rs/embassy.git",  rev = "d5badb9", version = "0.5.0", features = ["task-arena-size-1024", "arch-cortex-m", "executor-thread", "defmt", "integrated-timers", "executor-interrupt"] }
embassy-sync = {  git = "https://github.com/embassy-rs/embassy.git", rev = "d5badb9", version = "0.6.0" }
embassy-rp = {  git = "https://github.com/embassy-rs/embassy.git", rev = "d5badb9", features = ["defmt", "unstable-pac", "time-driver", "critical-section-impl"]}
embassy-futures = { git = "https://github.com/embassy-rs/embassy.git", rev = "d5badb9", version="0.1.1"}
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", rev = "d5badb9", version = "0.3.0", features = ["defmt", "defmt-timestamp-uptime"] }

thiserror = { version = "1.0.50", package = "thiserror-core", default-features = false }

static_cell = "2"
portable-atomic = { version = "1.5", features = ["critical-section"] }
heapless = "0.8"
